server:
  port: 8031

spring:
  application:
    name: subscribe
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.247.140:3306/mdp_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
    mapper-locations: classpath*:/mapper/*.xml
    type-aliases-package: com.hongke.file.excel.dao

tablename: mapping_info
filepath: D:\2_work_for_own\projects-open\easyexcel-header-export-by-comments\file\